### ISSUE TITLE
Investigate FIPS incompatibility for Strimzi container

### ISSUE THREAD

**Issue by michalvavrik** [quarkus-qe/quarkus-test-suite#1284]
`io.quarkus.ts.messaging.kafka.reactive.streams.SslAlertMonitorIT` is disabled on FIPS compatible machines as strimzi container fails to start with exception

```
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore src/test/resources/kafka-truststore.p12 of type PKCS12
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:375)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:347)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createTruststore(DefaultSslEngineFactory.java:320)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:168)
	at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:140)
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
	at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:73)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:511)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:454)
	... 78 more
Caused by: java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
	at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:839)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2074)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:372)
	... 89 more
Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.base/java.security.Security.getImpl(Security.java:779)
	at java.base/java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:158)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:833)
	... 93 more
```

I tried to add `kafka.ssl.engine.factory.class=org.apache.kafka.common.security.auth.SslEngineFactory` to container properties but it only moved to unknown provider for the same algorithm.

This test was [enabled on FIPS](https://github.com/quarkus-qe/quarkus-test-suite/pull/869) when [upstream issue was fixed](https://github.com/quarkusio/quarkus/issues/23964), however only Quakus issue was fixed. I tested Quarkus integration test referred in the issue and it's Strimzi container also doesn't start for same reasons.

I tried it with 0.33 and 0.35 and while exception changed, our algorithm is not supported. I believe we need to regenerate it as described here https://strimzi.io/blog/2023/01/25/running-apache-kafka-on-fips-enabled-kubernetes-cluster/

**Comment by michalvavrik** [comment]
I fixed this.
