### ISSUE TITLE
Investigate io.quarkus.ts.http.minimum.DevModeHttpMinimumIT failure in GH CI

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#511]
Investigate io.quarkus.ts.http.minimum.DevModeHttpMinimumIT failure in GH CI

```
13:12:15,044 INFO  Running command: mvn -e -Dquarkus.profile=DevModeHttpMinimumIT -Dmongodb.image=quay.io/bitnami/mongodb:5.0 -Dpostgresql.13.image=quay.io/bitnami/postgresql:13.5.0 -Dts.global.s2i.quarkus.native.builder.image=quay.io/quarkus/ubi-quarkus-native-s2i:21.3-java11 -Dkeycloak.image=quay.io/keycloak/keycloak:15.0.1 -Dmariadb.10.image=quay.io/bitnami/mariadb:10.6 -Drhsso.73.image=registry.access.redhat.com/redhat-sso-7/sso73-openshift -Dall-modules=true -Doracle.image=gvenzl/oracle-xe:21-slim -Dspring.cloud.server.image=quay.io/quarkusqeteam/spring-cloud-config-server:3.0 -Dmysql.57.image=quay.io/bitnami/mysql:5.7.32 -Dinclude.quarkus-cli-tests=true -Ddb2.image=quay.io/quarkusqeteam/db2:11.5.5.0 -Dprofile.id=jvm -Dts.quarkus.cli.cmd=/home/runner/work/quarkus-test-suite/quarkus-test-suite/quarkus-dev-cli -Dmssql.image=mcr.microsoft.com/mssql/rhel/server:2019-latest -Dconsul.image=quay.io/bitnami/consul:1.11.2 -Dinfinispan.expected-log=Infinispan Server.*started in -Dwiremock.image=quay.io/ocpmetal/wiremock -Dinfinispan.image=quay.io/infinispan/server:12.1 -DlocalRepository=/home/runner/.m2/repository -Dredis.image=quay.io/bitnami/redis:6.0 -Dts.global.s2i.quarkus.jvm.builder.image=registry.access.redhat.com/ubi8/openjdk-11:latest -Dmariadb.102.image=registry.access.redhat.com/rhscl/mariadb-102-rhel7 -Dmysql.80.image=registry.access.redhat.com/rhscl/mysql-80-rhel7 -Dcheckstyle.skip -DskipITs=true -Dquarkus.log.console.format=%d{HH:mm:ss,SSS} %s%e%n -Dquarkus.http.port=1101 -Ddebug=false quarkus:dev
13:12:19,064 INFO  [app] [INFO] Error stacktraces are turned on.
13:12:19,065 INFO  [app] [INFO] Scanning for projects...
13:12:19,065 INFO  [app] [INFO] 
13:12:19,065 INFO  [app] [INFO] -------------------< io.quarkus.ts.qe:http-minimum >--------------------
13:12:19,065 INFO  [app] [INFO] Building Quarkus QE TS: HTTP: minimum 1.0.0-SNAPSHOT
13:12:19,066 INFO  [app] [INFO] --------------------------------[ jar ]---------------------------------
13:12:19,066 INFO  [app] [INFO] 
13:12:19,066 INFO  [app] [INFO] --- quarkus-maven-plugin:999-SNAPSHOT:dev (default-cli) @ http-minimum ---
13:12:19,066 INFO  [app] [INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources) @ http-minimum
13:12:19,066 INFO  [app] [INFO] Using 'UTF-8' encoding to copy filtered resources.
13:12:19,066 INFO  [app] [INFO] Copying 3 resources
13:12:19,067 INFO  [app] [INFO] Invoking io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:generate-code) @ http-minimum
13:12:23,067 INFO  [app] [INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.9.0:compile) @ http-minimum
13:12:23,068 INFO  [app] [INFO] Changes detected - recompiling the module!
13:12:23,068 INFO  [app] [INFO] Compiling 2 source files to /home/runner/work/quarkus-test-suite/quarkus-test-suite/http/http-minimum/target/DevModeHttpMinimumIT/app/target/classes
13:12:23,068 INFO  [app] [INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources) @ http-minimum
13:12:23,068 INFO  [app] [INFO] Using 'UTF-8' encoding to copy filtered resources.
13:12:23,068 INFO  [app] [INFO] Copying 2 resources
13:12:23,069 INFO  [app] [INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.9.0:testCompile) @ http-minimum
13:12:23,069 INFO  [app] [INFO] Changes detected - recompiling the module!
13:12:23,069 INFO  [app] [INFO] Compiling 10 source files to /home/runner/work/quarkus-test-suite/quarkus-test-suite/http/http-minimum/target/DevModeHttpMinimumIT/app/target/test-classes
13:12:27,070 INFO  [app] Press [h] for more options>
13:12:27,071 INFO  [app] Tests paused
13:12:27,071 INFO  [app] Press [r] to resume testing, [h] for more options>
13:12:27,072 INFO  [app] Press [r] to resume testing, [o] Toggle test output, [h] for more options>
13:12:27,072 INFO  [app] __  ____  __  _____   ___  __ ____  ______ 
13:12:27,073 INFO  [app]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
13:12:27,073 INFO  [app]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
13:12:27,074 INFO  [app] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
13:12:27,074 INFO  [app] 13:12:25,596 test-http 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 2.270s. Listening on: http://localhost:1101
13:12:27,074 INFO  [app] 13:12:25,601 Profile DevModeHttpMinimumIT activated. Live Coding activated.
13:12:27,074 INFO  [app] 13:12:25,602 Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
13:12:28,202 INFO  [app] Service started (Quarkus DEV mode)
13:12:29,024 INFO  ## Running test DevModeHttpMinimumIT.shouldDetectNewTests()
2022-02-02 13:12:34,863 INFO  [org.ecl.jet.uti.log] (JS executor for com.gargoylesoftware.htmlunit.WebClient@671ea6ff) Logging initialized @28236ms to org.eclipse.jetty.util.log.Slf4jLog
13:12:35,089 INFO  [app] 13:12:32,664 Restarting quarkus due to changes in HelloResource.class.
13:12:35,090 INFO  [app] 13:12:32,676 test-http stopped in 0.011s
13:12:35,090 INFO  [app] __  ____  __  _____   ___  __ ____  ______ 
13:12:35,090 INFO  [app]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
13:12:35,090 INFO  [app]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
13:12:35,091 INFO  [app] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
13:12:35,091 INFO  [app] 13:12:32,969 test-http 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.285s. Listening on: http://localhost:1101
13:12:35,091 INFO  [app] 13:12:32,970 Profile DevModeHttpMinimumIT activated. Live Coding activated.
13:12:35,091 INFO  [app] 13:12:32,970 Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
13:12:35,091 INFO  [app] 13:12:32,970 Live reload total time: 0.837s 
13:12:39,092 INFO  [app] Running tests for the first time
13:12:39,093 INFO  [app] Press [h] for more options>
13:12:39,094 INFO  [app] Press [o] Toggle test output, [h] for more options>
13:12:39,094 INFO  [app] 13:12:38,377 Internal error running tests: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.quarkus.ts.http.minimum.HelloResourceTest
13:12:39,094 INFO  [app] 	at io.quarkus.deployment.dev.testing.JunitTestRunner.prepare(JunitTestRunner.java:418)
13:12:39,094 INFO  [app] 	at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:83)
13:12:39,094 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:345)
13:12:39,095 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:304)
13:12:39,095 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:829)
13:12:39,095 INFO  [app] Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.quarkus.ts.http.minimum.HelloResourceTest
13:12:39,095 INFO  [app] 	at io.quarkus.deployment.dev.testing.JunitTestRunner.discoverTestClasses(JunitTestRunner.java:593)
13:12:39,095 INFO  [app] 	at io.quarkus.deployment.dev.testing.JunitTestRunner.prepare(JunitTestRunner.java:146)
13:12:39,095 INFO  [app] 	... 4 more
13:12:39,096 INFO  [app] Caused by: java.lang.ClassNotFoundException: io.quarkus.ts.http.minimum.HelloResourceTest
13:12:39,096 INFO  [app] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
13:12:39,096 INFO  [app] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
13:12:39,096 INFO  [app] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
13:12:39,096 INFO  [app] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:464)
13:12:39,097 INFO  [app] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
13:12:39,098 INFO  [app] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:464)
13:12:39,098 INFO  [app] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
13:12:39,098 INFO  [app] 	at io.quarkus.deployment.dev.testing.JunitTestRunner.discoverTestClasses(JunitTestRunner.java:591)
13:12:39,098 INFO  [app] 	... 5 more
13:12:39,098 INFO  [app] 13:12:38,470 Internal error running tests: java.lang.IllegalStateException: Tests already in progress
13:12:39,098 INFO  [app] 	at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:49)
13:12:39,099 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:345)
13:12:39,099 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:304)
13:12:39,099 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:829)
13:12:39,099 INFO  [app] 13:12:38,657 Internal error running tests: java.lang.IllegalStateException: Tests already in progress
13:12:39,099 INFO  [app] 	at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:49)
13:12:39,099 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:345)
13:12:39,100 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:304)
13:12:39,100 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:829)
13:13:07,411 INFO  ## Running test DevModeHttpMinimumIT.shouldDetectChanges()
13:13:11,104 INFO  [app] 13:13:08,511 Internal error running tests: java.lang.IllegalStateException: Tests already in progress
13:13:11,104 INFO  [app] 	at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:49)
13:13:11,104 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:345)
13:13:11,105 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:304)
13:13:11,106 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:829)
13:13:11,106 INFO  [app] 13:13:09,297 Restarting quarkus due to changes in HelloResource.class.
13:13:11,106 INFO  [app] 13:13:09,309 test-http stopped in 0.003s
13:13:11,107 INFO  [app] __  ____  __  _____   ___  __ ____  ______ 
13:13:11,107 INFO  [app]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
13:13:11,108 INFO  [app]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
13:13:11,108 INFO  [app] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
13:13:11,108 INFO  [app] 13:13:09,747 test-http 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.414s. Listening on: http://localhost:1101
13:13:11,109 INFO  [app] 13:13:09,748 Profile DevModeHttpMinimumIT activated. Live Coding activated.
13:13:11,109 INFO  [app] 13:13:09,755 Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
13:13:11,110 INFO  [app] 13:13:09,756 Live reload total time: 0.460s 
13:13:11,110 INFO  [app] 13:13:10,922 Internal error running tests: java.lang.IllegalStateException: Tests already in progress
13:13:11,110 INFO  [app] 	at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:49)
13:13:11,111 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:345)
13:13:11,111 INFO  [app] 	at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:304)
13:13:11,111 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:829)
13:13:13,022 INFO  [app] 13:13:11,695 Restarting quarkus due to changes in HelloResource.class.
13:13:13,023 INFO  [app] 13:13:11,698 test-http stopped in 0.003s
13:13:13,023 INFO  [app] __  ____  __  _____   ___  __ ____  ______ 
13:13:13,023 INFO  [app]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
13:13:13,023 INFO  [app]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
13:13:13,023 INFO  [app] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
13:13:13,024 INFO  [app] 13:13:11,983 test-http 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.278s. Listening on: http://localhost:1101
13:13:13,024 INFO  [app] 13:13:11,984 Profile DevModeHttpMinimumIT activated. Live Coding activated.
13:13:13,024 INFO  [app] 13:13:11,984 Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
13:13:13,024 INFO  [app] 13:13:11,984 Live reload total time: 0.290s 
13:13:16,040 INFO  [app] Service stopped (Quarkus DEV mode)
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 68.041 s <<< FAILURE! - in io.quarkus.ts.http.minimum.DevModeHttpMinimumIT
```

e.g. https://github.com/quarkus-qe/quarkus-test-suite/runs/5036557458?check_suite_focus=true

**Comment by rsvoboda** [comment]
Another fail in http-minimal: `Error:    DevModeHttpMinimumIT.shouldDetectNewTests:50 » ConditionTimeout Assertion cond...`

**Comment by rsvoboda** [comment]
FYI .. local run of `mvn clean verify -pl http/http-minimum` passes for me, do seems like GH Action issue

**Comment by jsmrcka** [comment]
I was able to reproduce the error after switching my local env from `AdoptOpenJDK-11.0.11+9` to `Temurin-11.0.14+9` (the same JDK as in GH actions).

**Comment by gsmet** [comment]
Interesting. @stuartwdouglas any idea?

**Comment by stuartwdouglas** [comment]
I think this should fix it: https://github.com/quarkusio/quarkus/pull/23468

**Comment by rsvoboda** [comment]
Failures are no longer seen in daily runs, closing. Thank you for the fix.
