### ISSUE TITLE
Mssql + Openshift ignore required `quarkus.datasource.jdbc.additional-jdbc-properties.trustServerCertificate` property

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-suite#793]
This issue requires more investigation:

Reproducer: 

Quarkus: Upstream 
TestSuite: quarkus-test-suite

```
mvn clean verify -Dall-modules -Dopenshift -pl sql-db/sql-app -Dit.test=OpenShiftMssqlDatabaseIT
```

Error:
```
19:58:26,892 INFO  [app] ERROR: Failed to start application (with profile prod)
19:58:26,892 INFO  [app] java.util.NoSuchElementException: SRCFG00014: The config property quarkus.datasource.jdbc.additional-jdbc-properties.trustservercertificate is required but it could not be found in any config source
19:58:26,892 INFO  [app]        at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:282)
19:58:26,892 INFO  [app]        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:239)
19:58:26,893 INFO  [app]        at io.quarkus.runtime.generated.Config.rtParseKey:quarkus:datasource:jdbc:additional-jdbc-properties:*(Unknown Source)
19:58:26,893 INFO  [app]        at io.quarkus.runtime.generated.Config.rtParseKey:quarkus:datasource:jdbc:additional-jdbc-properties(Unknown Source)
19:58:26,893 INFO  [app]        at io.quarkus.runtime.generated.Config.rtParseKey:quarkus:datasource:jdbc(Unknown Source)

```

**Comment by michalvavrik** [comment]
closed by https://github.com/quarkus-qe/quarkus-test-suite/pull/794
